# Generated by Django 6.0.7 on 2026-07-10 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0004_alter_activity_options_activitybooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.sport')),
            ],
        ),
    ]
