# Generated by Django 6.0.7 on 2026-07-10 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0005_addon'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('add_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.addon')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.booking')),
            ],
        ),
    ]
