# Generated by Django 6.0.7 on 2026-07-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0010_coachavailability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachavailability',
            options={'verbose_name_plural': 'Coach Availabilities'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='activitybooking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
