# Generated by Django 6.0.7 on 2026-07-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0012_alter_activitybooking_status_alter_checkin_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=20),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
