# Generated by Django 6.0.7 on 2026-07-11 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0016_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courts.coach'),
        ),
    ]
